"""empty message

Revision ID: 301be44fd672
Revises: 36b93d81ad60
Create Date: 2015-02-18 12:09:17.849029

"""

# revision identifiers, used by Alembic.
revision = '301be44fd672'
down_revision = '36b93d81ad60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loguser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jmeno', sa.String(), nullable=False),
    sa.Column('prijmeni', sa.String(), nullable=False),
    sa.Column('pohlavi', sa.Boolean(name='zena'), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_loguser'),
    sqlite_autoincrement=True
    )
    op.create_index('ix_loguser_klokocnik', 'loguser', ['klokocnik'], unique=False)
    ### end Alembic commands ###




def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loguser_klokocnik', table_name='loguser')
    op.drop_table('loguser')
    ### end Alembic commands ###
